CREATE TABLE ACTOR (
  ACTOR_ID int(11) NOT NULL AUTO_INCREMENT,
  FIRSTNAME varchar(45) DEFAULT NULL,
  MIDNAME varchar(45) DEFAULT NULL,
  LASTNAME varchar(45) DEFAULT NULL,
  BIRTH_DAY datetime DEFAULT NULL,
  PRIMARY KEY (ACTOR_ID)
)

CREATE TABLE DIRECTOR (
  DIRECTOR_ID int(11) NOT NULL AUTO_INCREMENT,
  FIRSTNAME varchar(45) DEFAULT NULL,
  MIDNAME varchar(45) DEFAULT NULL,
  LASTNAME varchar(45) DEFAULT NULL,
  BIRTH_DAY datetime DEFAULT NULL,
  PRIMARY KEY (DIRECTOR_ID)
)

CREATE TABLE FILM (
  FILM_ID int(11) NOT NULL AUTO_INCREMENT,
  RELEASE_DATE datetime DEFAULT NULL,
  RUNNING_TIME int(11) DEFAULT NULL,
  TITLE varchar(100) DEFAULT NULL,
  PRIMARY KEY (FILM_ID)
)

CREATE TABLE STARRING (
	ACTOR_ID int(11) DEFAULT NULL,
	FILM_ID int(11) DEFAULT NULL,
	FOREIGN KEY (ACTOR_ID) REFERENCES ACTOR(ACTOR_ID),
	FOREIGN KEY (FILM_ID) REFERENCES FILM(FILM_ID) 
		ON DELETE CASCADE
		ON UPDATE CASCADE
)

CREATE TABLE DIRECTED (
	DIRECTOR_ID int(11) DEFAULT NULL,
	FILM_ID int(11) DEFAULT NULL,
	FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTOR(DIRECTOR_ID),
	FOREIGN KEY (FILM_ID) REFERENCES FILM(FILM_ID)	
		ON DELETE CASCADE
		ON UPDATE CASCADE
)